# Jupyter para ex. 2 sem ecrã. Arranque no host: run_jupyter.sh .
FROM quay.io/jupyter/minimal-notebook:latest

USER root
COPY requirements.txt /tmp/requirements-ex02-sem.txt
RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r /tmp/requirements-ex02-sem.txt \
  && fix-permissions "${CONDA_DIR}" \
  && fix-permissions "/home/${NB_USER}"

USER ${NB_UID}
