services:
  app:
    build: .
    container_name: exercicio_14_tutorgraph
    ports:
      - "8014:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
