services:
  app:
    build: .
    container_name: exercicio_18_api_factory
    ports:
      - "8018:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
